export const styles = {
  app: {
    position: "fixed",
    inset: 0,
    overflow: "hidden",
    background: "#050608",
    color: "#fff",
    fontFamily:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  battle: {
    position: "relative",
    width: "100%",
    height: "100%",
    overflow: "hidden",
  },
  layout: {
    position: "absolute",
    inset: 0,
    display: "flex",
  },
  layoutPortrait: {
    flexDirection: "column",
  },
  layoutLandscape: {
    flexDirection: "row",
  },
  /** Soft-freeze overlay when contender attachment card is open (under card, above media) */
  attachmentDim: {
    position: "absolute",
    inset: 0,
    zIndex: 6,
    pointerEvents: "none",
    background:
      "radial-gradient(ellipse 92% 72% at 50% 48%, rgba(3,5,12,0.58), rgba(2,3,8,0.38)), rgba(2,3,6,0.28)",
    transition: "opacity 0.28s ease",
  },
  slot: {
    position: "relative",
    overflow: "hidden",
    minWidth: 0,
    minHeight: 0,
    background: "#050608",
  },
  slotPortrait: {
    flex: "0 0 50%",
    height: "50%",
  },
  slotLandscape: {
    flex: "0 0 50%",
    width: "50%",
  },
  surface: {
    position: "absolute",
    inset: 0,
    overflow: "hidden",
    background: "#07080b",
  },
  mediaWrap: {
    position: "absolute",
    inset: 0,
    transition: "filter 180ms ease",
    overflow: "hidden",
  },
  mediaFill: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    objectPosition: "center center",
    userSelect: "none",
    WebkitUserDrag: "none",
    background: "#0b0b0d",
    display: "block",
  },
  gestureLayer: {
    position: "absolute",
    inset: 0,
    zIndex: 3,
    background: "transparent",
    touchAction: "none",
  },
  peekWrap: {
    position: "absolute",
    pointerEvents: "none",
    zIndex: 12,
  },
  peekAnchorFirstPortrait: {
    top: 0,
    left: 0,
    right: 0,
    width: "100%",
    height: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "max(12px, env(safe-area-inset-top))",
    boxSizing: "border-box",
  },
  peekAnchorSecondPortrait: {
    top: "50%",
    left: 0,
    right: 0,
    width: "100%",
    height: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "max(12px, env(safe-area-inset-bottom))",
    boxSizing: "border-box",
  },
  peekAnchorFirstLandscape: {
    top: 0,
    bottom: 0,
    left: 0,
    width: "50%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "max(12px, env(safe-area-inset-left))",
    boxSizing: "border-box",
  },
  peekAnchorSecondLandscape: {
    top: 0,
    bottom: 0,
    left: "50%",
    width: "50%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "max(12px, env(safe-area-inset-right))",
    boxSizing: "border-box",
  },
  peekCard: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    pointerEvents: "auto",
    width: "min(300px, calc(100vw - 28px))",
    maxWidth: "min(300px, 92%)",
    margin: "0 auto",
    borderRadius: 22,
    border: "1px solid rgba(255,255,255,.08)",
    background: "linear-gradient(172deg, rgba(12,14,20,.98) 0%, rgba(5,7,11,.95) 48%, rgba(4,5,9,.97) 100%)",
    backdropFilter: "blur(24px)",
    WebkitBackdropFilter: "blur(24px)",
    padding: "20px 42px 18px 18px",
    boxShadow: "0 28px 72px rgba(0,0,0,.52), inset 0 1px 0 rgba(255,255,255,.04)",
  },
  peekClose: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 30,
    height: 30,
    padding: 0,
    lineHeight: "28px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,.12)",
    background: "rgba(255,255,255,.06)",
    color: "#fff",
    fontSize: 20,
    fontWeight: 300,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  peekBroadcastEyebrow: {
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: "0.34em",
    textTransform: "uppercase",
    opacity: 0.92,
    marginBottom: 14,
    textShadow: "0 1px 18px rgba(0,0,0,.35)",
  },
  peekAthlete: {
    fontSize: 22,
    fontWeight: 800,
    letterSpacing: "-0.045em",
    lineHeight: 1.08,
    marginBottom: 6,
  },
  peekClipTitle: {
    fontSize: 12,
    fontWeight: 600,
    opacity: 0.5,
    lineHeight: 1.4,
    marginBottom: 2,
  },
  peekNarrativeBlock: {
    marginTop: 16,
    marginBottom: 2,
  },
  peekNarrativeLine: {
    margin: 0,
    padding: 0,
    fontSize: 16,
    fontWeight: 800,
    letterSpacing: "-0.028em",
    lineHeight: 1.36,
    opacity: 0.96,
    fontStyle: "normal",
  },
  peekDividerSoft: {
    height: 1,
    margin: "18px 0 14px",
    background: "linear-gradient(90deg, transparent 4%, rgba(255,255,255,.09) 50%, transparent 96%)",
    opacity: 0.85,
  },
  peekStatusSnapshot: {
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "-0.015em",
    lineHeight: 1.45,
    opacity: 0.78,
    marginBottom: 6,
  },
  peekRecordQuiet: {
    fontSize: 11,
    fontWeight: 600,
    opacity: 0.38,
    letterSpacing: "0.02em",
    marginBottom: 8,
  },
  peekRatingFootnote: {
    fontSize: 9,
    fontWeight: 600,
    opacity: 0.26,
    letterSpacing: "0.04em",
    marginBottom: 12,
  },
  peekAffiliation: {
    fontSize: 10,
    fontWeight: 600,
    opacity: 0.36,
    lineHeight: 1.5,
    letterSpacing: "0.02em",
    marginBottom: 14,
  },
  peekFollowBtn: {
    width: "100%",
    margin: 0,
    padding: "12px 14px",
    borderRadius: 14,
    border: "1px solid rgba(255,255,255,.1)",
    background: "rgba(255,255,255,.05)",
    color: "#fff",
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    cursor: "pointer",
  },
  peekFollowHint: {
    fontSize: 9,
    fontWeight: 600,
    opacity: 0.32,
    textAlign: "center",
    marginTop: 8,
    letterSpacing: "0.03em",
    lineHeight: 1.35,
  },
  scrim: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    background:
      "linear-gradient(180deg, rgba(0,0,0,0.02) 0%, rgba(0,0,0,0.07) 36%, rgba(0,0,0,0.22) 100%)",
  },
  vignette: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    boxShadow: "inset 0 0 68px rgba(0,0,0,0.22)",
  },
  inactive: {
    position: "absolute",
    inset: 0,
    background: "rgba(0,0,0,0.24)",
    pointerEvents: "none",
  },
  seamPortrait: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "50%",
    height: 2,
    zIndex: 6,
    pointerEvents: "none",
    transform: "translateY(-1px)",
  },
  seamLandscape: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "50%",
    width: 2,
    zIndex: 6,
    pointerEvents: "none",
    transform: "translateX(-1px)",
  },
  arenaIntroSeamGlowWrap: {
    position: "absolute",
    inset: 0,
    zIndex: 7,
    pointerEvents: "none",
  },
  arenaIntroSeamConvergePortrait: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "50%",
    height: "min(26vh, 168px)",
    transform: "translateY(-50%)",
    pointerEvents: "none",
  },
  arenaIntroSeamCorePortrait: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "50%",
    height: 2,
    transform: "translateY(-50%)",
    pointerEvents: "none",
  },
  arenaIntroSeamConvergeLandscape: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "50%",
    width: "min(26vw, 168px)",
    transform: "translateX(-50%)",
    pointerEvents: "none",
  },
  arenaIntroSeamCoreLandscape: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "50%",
    width: 2,
    transform: "translateX(-50%)",
    pointerEvents: "none",
  },
  /** Persistent soft arena tint on the divide — below VS, above seam line */
  battleSeamAura: {
    position: "absolute",
    pointerEvents: "none",
    zIndex: 7,
    filter: "saturate(1.08)",
  },
  battleSeamAuraPortrait: {
    left: "14%",
    right: "14%",
    top: "42%",
    bottom: "42%",
  },
  battleSeamAuraLandscape: {
    left: "42%",
    right: "42%",
    top: "14%",
    bottom: "14%",
  },
  vsLayer: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "none",
    zIndex: 8,
  },
  vsDiamond: {
    width: 40,
    height: 40,
    transform: "rotate(45deg)",
    borderRadius: 6,
    border: "1px solid",
    background: "linear-gradient(148deg, rgba(13,15,21,.93) 0%, rgba(6,8,12,.91) 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  vsInner: {
    transform: "rotate(-45deg)",
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: "0.32em",
    marginLeft: 1,
    opacity: 0.88,
  },
  arenaLabelWrap: {
    position: "absolute",
    inset: 0,
    zIndex: 30,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "none",
  },
  arenaLabelStack: {
    position: "relative",
    display: "inline-flex",
    flexDirection: "column",
    alignItems: "center",
    pointerEvents: "none",
    maxWidth: "min(calc(100vw - 32px), 300px)",
  },
  arenaLabel: {
    display: "inline-flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "12px 18px",
    width: "max-content",
    maxWidth: "100%",
    margin: 0,
    borderRadius: 0,
    clipPath: "polygon(2.5% 6%, 97.5% 6%, 100% 14%, 100% 86%, 97.5% 94%, 2.5% 94%, 0% 86%, 0% 14%)",
    WebkitClipPath: "polygon(2.5% 6%, 97.5% 6%, 100% 14%, 100% 86%, 97.5% 94%, 2.5% 94%, 0% 86%, 0% 14%)",
    background:
      "linear-gradient(180deg, rgba(10,12,18,.72) 0%, rgba(7,8,13,.82) 48%, rgba(5,6,10,.86) 100%)",
    backdropFilter: "blur(16px) saturate(1.12)",
    WebkitBackdropFilter: "blur(16px) saturate(1.12)",
    border: "1px solid rgba(255,255,255,.056)",
    boxSizing: "border-box",
    textAlign: "center",
    isolation: "isolate",
  },
  arenaLabelTitle: {
    display: "block",
    flex: "1 1 auto",
    minWidth: 0,
    fontSize: 9,
    fontWeight: 600,
    letterSpacing: "0.38em",
    textTransform: "uppercase",
    lineHeight: 1.12,
    opacity: 0.9,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  arenaLabelChevron: {
    flexShrink: 0,
    fontSize: 7,
    lineHeight: 1,
    opacity: 0.38,
    marginTop: 1,
    transform: "translateY(0.5px)",
  },
  arenaLabelHint: {
    position: "absolute",
    left: "50%",
    top: "100%",
    marginTop: 5,
    transform: "translateX(-50%)",
    fontSize: 7,
    fontWeight: 500,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "rgba(255,255,255,.36)",
    whiteSpace: "nowrap",
    pointerEvents: "none",
    userSelect: "none",
  },
  arenaPickerOverlay: {
    position: "absolute",
    inset: 0,
    zIndex: 31,
    background: "rgba(3,4,8,.32)",
    backdropFilter: "blur(6px)",
    WebkitBackdropFilter: "blur(6px)",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    paddingTop: 52,
    paddingLeft: 12,
    paddingRight: 12,
  },
  arenaPickerCard: {
    width: "min(420px, 100%)",
    maxHeight: "58vh",
    borderRadius: 16,
    border: "1px solid rgba(255,255,255,.08)",
    background: "rgba(8,10,14,.92)",
    backdropFilter: "blur(14px)",
    WebkitBackdropFilter: "blur(14px)",
    boxShadow: "0 18px 50px rgba(0,0,0,.36)",
    overflow: "hidden",
  },
  arenaPickerInput: {
    width: "100%",
    border: "none",
    borderBottom: "1px solid rgba(255,255,255,.08)",
    background: "rgba(255,255,255,.03)",
    color: "#fff",
    padding: "11px 12px",
    fontSize: 13,
    outline: "none",
    boxSizing: "border-box",
  },
  arenaPickerList: {
    maxHeight: "48vh",
    overflowY: "auto",
    padding: 6,
  },
  arenaPickerItem: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 9,
    border: "none",
    borderRadius: 10,
    background: "transparent",
    color: "#fff",
    padding: "9px 10px",
    textAlign: "left",
    cursor: "pointer",
  },
  arenaPickerItemActive: {
    background: "rgba(255,255,255,.08)",
  },
  arenaPickerDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    flex: "0 0 8px",
  },
  arenaPickerText: {
    fontSize: 13,
    fontWeight: 700,
  },
  detailsWrap: {
    position: "absolute",
    inset: 0,
    zIndex: 18,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    padding: 16,
    pointerEvents: "none",
  },
  detailsCard: {
    width: "min(480px, 92vw)",
    borderRadius: 20,
    border: "1px solid rgba(255,255,255,.08)",
    background: "rgba(8,10,14,.72)",
    backdropFilter: "blur(18px)",
    WebkitBackdropFilter: "blur(18px)",
    padding: 14,
    boxShadow: "0 18px 60px rgba(0,0,0,.35)",
  },
  detailsTitle: {
    fontSize: 18,
    fontWeight: 800,
    lineHeight: 1.08,
    marginBottom: 6,
  },
  detailsCreator: {
    fontSize: 13,
    opacity: 0.72,
    marginBottom: 10,
  },
  pillRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
  },
  pill: {
    padding: "7px 10px",
    borderRadius: 999,
    background: "rgba(255,255,255,.06)",
    border: "1px solid rgba(255,255,255,.06)",
    fontSize: 12,
    fontWeight: 700,
  },
  detailsArena: {
    fontSize: 12,
    fontWeight: 700,
  },
  championWrap: {
    position: "absolute",
    inset: 0,
    zIndex: 25,
    background: "rgba(4,6,10,.34)",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  championCard: {
    width: "min(400px, 90vw)",
    borderRadius: 24,
    border: "1px solid rgba(255,255,255,.08)",
    background: "linear-gradient(180deg, rgba(14,18,25,.96), rgba(8,10,14,.96))",
    padding: "24px 22px 22px",
    textAlign: "center",
    boxShadow: "0 24px 80px rgba(0,0,0,.42)",
  },
  championMicro: {
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: "0.24em",
    opacity: 0.5,
    marginBottom: 12,
  },
  championTitle: {
    fontSize: 28,
    fontWeight: 800,
    lineHeight: 1.02,
    marginBottom: 8,
  },
  championCreator: {
    fontSize: 15,
    opacity: 0.72,
    marginBottom: 18,
  },
  championRule: {
    width: 72,
    height: 1,
    background: "rgba(255,255,255,.16)",
    margin: "0 auto 16px",
  },
  championSub: {
    fontSize: 14,
    lineHeight: 1.4,
    opacity: 0.7,
  },
  swipeZone: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 84,
    background: "transparent",
    touchAction: "none",
  },
  /** Leaderboard — portrait bottom sheet */
  lbSheetPortrait: {
    position: "absolute",
    left: "max(10px, env(safe-area-inset-left))",
    right: "max(10px, env(safe-area-inset-right))",
    bottom: -2,
    maxHeight: "min(560px, calc(100vh - env(safe-area-inset-top) - env(safe-area-inset-bottom) - 56px))",
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    background: "linear-gradient(168deg, rgba(18,20,28,.94) 0%, rgba(8,10,14,.9) 42%, rgba(6,8,12,.92) 100%)",
    backdropFilter: "blur(22px)",
    WebkitBackdropFilter: "blur(22px)",
    border: "1px solid rgba(255,255,255,.08)",
    boxShadow: "0 -32px 88px rgba(0,0,0,.48), inset 0 1px 0 rgba(255,255,255,.07)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  /** Leaderboard — landscape: full-screen overlay host (centered card inside) */
  lbLandOverlay: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: "max(12px, env(safe-area-inset-left))",
    paddingRight: "max(12px, env(safe-area-inset-right))",
    paddingTop: "max(12px, env(safe-area-inset-top))",
    paddingBottom: "max(12px, env(safe-area-inset-bottom))",
  },
  lbLandBackdrop: {
    position: "absolute",
    inset: 0,
    background: "rgba(3,5,10,.7)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
  },
  /** Centered standings card (landscape overlay) */
  lbCardLandscape: {
    position: "relative",
    width: "min(560px, 86vw)",
    maxWidth: 560,
    maxHeight: "80vh",
    borderRadius: 24,
    background: "linear-gradient(198deg, rgba(22,24,32,.98) 0%, rgba(12,14,20,.96) 55%, rgba(8,10,14,.94) 100%)",
    backdropFilter: "blur(22px)",
    WebkitBackdropFilter: "blur(22px)",
    border: "1px solid rgba(255,255,255,.1)",
    boxShadow: "0 28px 100px rgba(0,0,0,.58), inset 0 1px 0 rgba(255,255,255,.07)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    zIndex: 1,
  },
  lbHandleTap: {
    flexShrink: 0,
    paddingTop: 12,
    paddingBottom: 8,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    border: "none",
    background: "transparent",
    width: "100%",
    color: "inherit",
  },
  lbHandle: {
    width: 36,
    height: 5,
    borderRadius: 999,
    background: "rgba(255,255,255,.14)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,.12)",
  },
  lbHeader: {
    flexShrink: 0,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 12,
    padding: "4px 18px 16px",
    borderBottom: "1px solid rgba(255,255,255,.05)",
  },
  lbEyebrow: {
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: "0.26em",
    opacity: 0.42,
    marginBottom: 7,
    fontWeight: 700,
  },
  lbArenaTitle: {
    fontSize: 20,
    fontWeight: 800,
    lineHeight: 1.05,
    letterSpacing: "-0.02em",
  },
  lbUpload: {
    width: 38,
    height: 38,
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,.1)",
    background: "rgba(255,255,255,.06)",
    color: "#fff",
    fontSize: 22,
    fontWeight: 300,
    cursor: "pointer",
    lineHeight: 1,
    flexShrink: 0,
  },
  lbListPortrait: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    WebkitOverflowScrolling: "touch",
    padding: "6px 14px calc(18px + env(safe-area-inset-bottom))",
    scrollbarWidth: "thin",
  },
  /** Scroll region inside landscape centered modal */
  lbListModal: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    WebkitOverflowScrolling: "touch",
    padding: "6px 14px 18px",
    scrollbarWidth: "thin",
  },
  lbRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 16,
    border: "1px solid rgba(255,255,255,.06)",
    background: "linear-gradient(135deg, rgba(255,255,255,.045) 0%, rgba(255,255,255,.018) 100%)",
    marginBottom: 8,
  },
  lbPodium1: {
    border: "1px solid rgba(255,255,255,.1)",
    background: "linear-gradient(135deg, rgba(255,255,255,.09) 0%, rgba(255,255,255,.028) 100%)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,.08)",
  },
  lbPodium2: {
    border: "1px solid rgba(255,255,255,.08)",
    background: "linear-gradient(135deg, rgba(255,255,255,.065) 0%, rgba(255,255,255,.022) 100%)",
  },
  lbPodium3: {
    border: "1px solid rgba(255,255,255,.07)",
    background: "linear-gradient(135deg, rgba(255,255,255,.055) 0%, rgba(255,255,255,.02) 100%)",
  },
  lbRowContender: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255,255,255,.08)",
    boxShadow: "inset 3px 0 0 rgba(255,255,255,.12)",
  },
  lbRank: {
    width: 30,
    fontSize: 12,
    fontWeight: 800,
    fontVariantNumeric: "tabular-nums",
    flexShrink: 0,
  },
  lbThumb: {
    width: 48,
    height: 48,
    borderRadius: 12,
    overflow: "hidden",
    flexShrink: 0,
    background: "rgba(0,0,0,.35)",
    border: "1px solid rgba(255,255,255,.08)",
    boxShadow: "inset 0 0 0 1px rgba(0,0,0,.2)",
  },
  lbThumbMedia: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    objectPosition: "center center",
    display: "block",
  },
  lbRowMain: {
    flex: 1,
    minWidth: 0,
  },
  lbRowTop: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  lbTitleBlock: {
    minWidth: 0,
    flex: 1,
  },
  lbItemTitle: {
    fontSize: 13,
    fontWeight: 800,
    lineHeight: 1.2,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  lbItemCreator: {
    fontSize: 11,
    opacity: 0.5,
    marginTop: 3,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  lbFollow: {
    fontSize: 9,
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    fontWeight: 700,
    opacity: 0.35,
    border: "1px solid rgba(255,255,255,.1)",
    borderRadius: 999,
    background: "rgba(255,255,255,.03)",
    color: "rgba(255,255,255,.55)",
    cursor: "not-allowed",
    padding: "5px 10px",
    flexShrink: 0,
    lineHeight: 1,
  },
  lbStats: {
    textAlign: "right",
    flexShrink: 0,
    minWidth: 64,
  },
  lbRating: {
    fontSize: 14,
    fontWeight: 800,
    fontVariantNumeric: "tabular-nums",
    letterSpacing: "-0.02em",
  },
  lbStatus: {
    fontSize: 10,
    opacity: 0.5,
    marginTop: 3,
    fontWeight: 600,
    letterSpacing: "0.04em",
  },
  uploadOverlay: {
    position: "absolute",
    inset: 0,
    zIndex: 32,
    background: "rgba(4,6,10,.52)",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    padding: 12,
  },
  uploadCard: {
    width: "min(720px, 100%)",
    maxHeight: "88vh",
    overflowY: "auto",
    borderRadius: 28,
    border: "1px solid rgba(255,255,255,.08)",
    background: "linear-gradient(180deg, rgba(13,17,24,.98), rgba(8,10,14,.98))",
    boxShadow: "0 24px 80px rgba(0,0,0,.45)",
    padding: 18,
  },
  uploadHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 14,
  },
  uploadEyebrow: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.2em",
    opacity: 0.46,
    marginBottom: 5,
  },
  uploadTitle: {
    fontSize: 26,
    fontWeight: 800,
    lineHeight: 1,
  },
  closeButton: {
    width: 34,
    height: 34,
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,.08)",
    background: "rgba(255,255,255,.04)",
    color: "#fff",
    fontSize: 22,
    cursor: "pointer",
  },
  uploadGrid: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    marginBottom: 14,
  },
  field: {
    display: "grid",
    gap: 6,
    fontSize: 12,
    fontWeight: 700,
    opacity: 0.84,
  },
  input: {
    width: "100%",
    borderRadius: 14,
    border: "1px solid rgba(255,255,255,.08)",
    background: "rgba(255,255,255,.04)",
    color: "#fff",
    padding: "12px 12px",
    outline: "none",
  },
  uploadButtons: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    marginBottom: 14,
  },
  uploadButton: {
    flex: 1,
    minWidth: 140,
    borderRadius: 14,
    border: "1px solid rgba(255,255,255,.08)",
    background: "rgba(255,255,255,.04)",
    color: "#fff",
    padding: "12px 14px",
    fontWeight: 800,
    cursor: "pointer",
  },
  previewBox: {
    borderRadius: 20,
    border: "1px solid rgba(255,255,255,.08)",
    background: "rgba(255,255,255,.03)",
    padding: 12,
    marginBottom: 14,
  },
  previewEmpty: {
    minHeight: 150,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    fontSize: 14,
    lineHeight: 1.5,
    opacity: 0.62,
    padding: 20,
  },
  cropHeader: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
    fontWeight: 800,
    fontSize: 13,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  battlePreviewFrame: {
    width: "100%",
    aspectRatio: "9 / 8",
    borderRadius: 18,
    overflow: "hidden",
    background: "#050608",
    border: "1px solid rgba(255,255,255,.12)",
    position: "relative",
    boxShadow: "inset 0 0 0 1px rgba(255,255,255,.04)",
  },
  previewBattleMedia: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    objectPosition: "center center",
    display: "block",
    background: "#08090c",
  },
  cropGuideVertical: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "50%",
    width: 1,
    background: "rgba(255,255,255,.18)",
    zIndex: 4,
    pointerEvents: "none",
  },
  cropGuideHorizontal: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "50%",
    height: 1,
    background: "rgba(255,255,255,.18)",
    zIndex: 4,
    pointerEvents: "none",
  },
  cropFrameLabel: {
    position: "absolute",
    right: 10,
    bottom: 10,
    zIndex: 5,
    padding: "5px 8px",
    borderRadius: 999,
    background: "rgba(0,0,0,.46)",
    border: "1px solid rgba(255,255,255,.12)",
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: "0.12em",
  },
  cropNote: {
    marginTop: 8,
    marginBottom: 10,
    fontSize: 12,
    opacity: 0.56,
  },
  trimRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 10,
    marginBottom: 12,
    fontSize: 12,
    opacity: 0.75,
  },
  sliderLabel: {
    display: "grid",
    gap: 6,
    fontSize: 12,
    fontWeight: 700,
    opacity: 0.72,
    marginBottom: 10,
  },
  slider: {
    width: "100%",
  },
  uploadActions: {
    display: "flex",
    gap: 10,
  },
  cancelButton: {
    flex: 1,
    borderRadius: 16,
    border: "1px solid rgba(255,255,255,.08)",
    background: "rgba(255,255,255,.04)",
    color: "#fff",
    padding: "12px 14px",
    fontWeight: 800,
    cursor: "pointer",
  },
  saveButton: {
    flex: 1,
    borderRadius: 16,
    border: "none",
    background: "linear-gradient(180deg, #7c3aed, #5b21b6)",
    color: "#fff",
    padding: "12px 14px",
    fontWeight: 800,
    cursor: "pointer",
  },
  onboardingWrap: {
    position: "absolute",
    inset: 0,
    zIndex: 29,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "max(16px, env(safe-area-inset-top)) max(14px, env(safe-area-inset-right)) max(16px, env(safe-area-inset-bottom)) max(14px, env(safe-area-inset-left))",
  },
  onboardingBackdrop: {
    position: "absolute",
    inset: 0,
    background:
      "radial-gradient(ellipse 88% 64% at 50% 48%, rgba(5,8,14,.18), rgba(2,3,8,.42)), rgba(1,2,6,.44)",
    backdropFilter: "blur(2px)",
    WebkitBackdropFilter: "blur(2px)",
  },
  onboardingCard: {
    position: "relative",
    width: "min(420px, calc(100vw - 28px))",
    borderRadius: 24,
    border: "1px solid rgba(255,255,255,.08)",
    background:
      "linear-gradient(170deg, rgba(14,18,26,.94) 0%, rgba(8,11,16,.92) 42%, rgba(4,6,10,.94) 100%)",
    boxShadow: "0 28px 90px rgba(0,0,0,.54), inset 0 1px 0 rgba(255,255,255,.05)",
    backdropFilter: "blur(18px)",
    WebkitBackdropFilter: "blur(18px)",
    padding: "22px 20px 18px",
    overflow: "hidden",
  },
  onboardingEyebrow: {
    fontSize: 10,
    letterSpacing: "0.34em",
    textTransform: "uppercase",
    fontWeight: 800,
    opacity: 0.7,
    marginBottom: 14,
  },
  onboardingTitle: {
    margin: 0,
    fontSize: 35,
    lineHeight: 0.98,
    letterSpacing: "-0.03em",
    fontWeight: 800,
  },
  onboardingSubcopy: {
    margin: "12px 0 0",
    fontSize: 14,
    lineHeight: 1.45,
    opacity: 0.72,
  },
  onboardingRule: {
    height: 1,
    margin: "16px 0 12px",
    background: "linear-gradient(90deg, transparent 2%, rgba(255,255,255,.11) 50%, transparent 98%)",
  },
  onboardingGestureList: {
    display: "grid",
    gap: 10,
  },
  onboardingGestureRow: {
    display: "grid",
    gap: 3,
  },
  onboardingGestureLabel: {
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: "0.18em",
    fontWeight: 700,
    opacity: 0.92,
  },
  onboardingGestureDetail: {
    fontSize: 13,
    lineHeight: 1.32,
    opacity: 0.64,
  },
  onboardingBeginButton: {
    width: "100%",
    marginTop: 17,
    borderRadius: 14,
    border: "1px solid rgba(255,255,255,.14)",
    background: "linear-gradient(180deg, rgba(255,255,255,.085), rgba(255,255,255,.04))",
    color: "#fff",
    padding: "12px 14px",
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: "0.24em",
    textTransform: "uppercase",
    cursor: "pointer",
  },
  fallback: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    padding: 22,
  },
  fallbackArena: {
    fontSize: 11,
    letterSpacing: "0.18em",
    opacity: 0.7,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  fallbackTitle: {
    fontSize: 30,
    fontWeight: 800,
    lineHeight: 1,
    marginBottom: 6,
  },
  fallbackCreator: {
    fontSize: 15,
    opacity: 0.72,
  },
  empty: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    padding: 24,
    background: "#050608",
  },
  emptyTitle: {
    fontSize: 26,
    fontWeight: 800,
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 15,
    lineHeight: 1.5,
    opacity: 0.68,
    maxWidth: 360,
    marginBottom: 18,
  },
  emptyButton: {
    borderRadius: 16,
    border: "none",
    background: "linear-gradient(180deg, #7c3aed, #5b21b6)",
    color: "#fff",
    padding: "12px 16px",
    fontWeight: 800,
    cursor: "pointer",
  },
};
