export const styles = {
  app: {
    position: "fixed",
    inset: 0,
    overflow: "hidden",
    background: "#050608",
    color: "#fff",
    fontFamily:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  battle: {
    position: "relative",
    width: "100%",
    height: "100%",
    overflow: "hidden",
  },
  layout: {
    position: "absolute",
    inset: 0,
    display: "flex",
  },
  layoutPortrait: {
    flexDirection: "column",
  },
  layoutLandscape: {
    flexDirection: "row",
  },
  slot: {
    position: "relative",
    overflow: "hidden",
    minWidth: 0,
    minHeight: 0,
    background: "#050608",
  },
  slotPortrait: {
    flex: "0 0 50%",
    height: "50%",
  },
  slotLandscape: {
    flex: "0 0 50%",
    width: "50%",
  },
  surface: {
    position: "absolute",
    inset: 0,
    overflow: "hidden",
    background: "#07080b",
  },
  mediaWrap: {
    position: "absolute",
    inset: 0,
    transition: "filter 180ms ease",
    overflow: "hidden",
  },
  mediaFill: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    objectPosition: "center center",
    userSelect: "none",
    WebkitUserDrag: "none",
    background: "#0b0b0d",
    display: "block",
  },
  gestureLayer: {
    position: "absolute",
    inset: 0,
    zIndex: 3,
    background: "transparent",
    touchAction: "none",
  },
  scrim: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    background:
      "linear-gradient(180deg, rgba(0,0,0,0.02) 0%, rgba(0,0,0,0.07) 36%, rgba(0,0,0,0.22) 100%)",
  },
  vignette: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    boxShadow: "inset 0 0 68px rgba(0,0,0,0.22)",
  },
  inactive: {
    position: "absolute",
    inset: 0,
    background: "rgba(0,0,0,0.24)",
    pointerEvents: "none",
  },
  seamPortrait: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "50%",
    height: 2,
    zIndex: 6,
    pointerEvents: "none",
    transform: "translateY(-1px)",
  },
  seamLandscape: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "50%",
    width: 2,
    zIndex: 6,
    pointerEvents: "none",
    transform: "translateX(-1px)",
  },
  vsLayer: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "none",
    zIndex: 8,
  },
  vsDiamond: {
    width: 40,
    height: 40,
    transform: "rotate(45deg)",
    borderRadius: 5,
    border: "1px solid",
    background: "rgba(0,0,0,0.88)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  vsInner: {
    transform: "rotate(-45deg)",
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: "0.2em",
    marginLeft: 2,
  },
  arenaLabelWrap: {
    position: "absolute",
    top: 14,
    left: 0,
    right: 0,
    zIndex: 30,
    display: "flex",
    justifyContent: "center",
    pointerEvents: "none",
  },
  arenaLabel: {
    padding: "7px 12px",
    borderRadius: 999,
    background: "rgba(8,10,14,.34)",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    border: "1px solid rgba(255,255,255,.06)",
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: "0.18em",
    textTransform: "uppercase",
  },
  detailsWrap: {
    position: "absolute",
    inset: 0,
    zIndex: 18,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    padding: 16,
    pointerEvents: "none",
  },
  detailsCard: {
    width: "min(480px, 92vw)",
    borderRadius: 20,
    border: "1px solid rgba(255,255,255,.08)",
    background: "rgba(8,10,14,.72)",
    backdropFilter: "blur(18px)",
    WebkitBackdropFilter: "blur(18px)",
    padding: 14,
    boxShadow: "0 18px 60px rgba(0,0,0,.35)",
  },
  detailsTitle: {
    fontSize: 18,
    fontWeight: 800,
    lineHeight: 1.08,
    marginBottom: 6,
  },
  detailsCreator: {
    fontSize: 13,
    opacity: 0.72,
    marginBottom: 10,
  },
  pillRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
  },
  pill: {
    padding: "7px 10px",
    borderRadius: 999,
    background: "rgba(255,255,255,.06)",
    border: "1px solid rgba(255,255,255,.06)",
    fontSize: 12,
    fontWeight: 700,
  },
  detailsArena: {
    fontSize: 12,
    fontWeight: 700,
  },
  championWrap: {
    position: "absolute",
    inset: 0,
    zIndex: 25,
    background: "rgba(4,6,10,.34)",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  championCard: {
    width: "min(400px, 90vw)",
    borderRadius: 24,
    border: "1px solid rgba(255,255,255,.08)",
    background: "linear-gradient(180deg, rgba(14,18,25,.96), rgba(8,10,14,.96))",
    padding: "24px 22px 22px",
    textAlign: "center",
    boxShadow: "0 24px 80px rgba(0,0,0,.42)",
  },
  championMicro: {
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: "0.24em",
    opacity: 0.5,
    marginBottom: 12,
  },
  championTitle: {
    fontSize: 28,
    fontWeight: 800,
    lineHeight: 1.02,
    marginBottom: 8,
  },
  championCreator: {
    fontSize: 15,
    opacity: 0.72,
    marginBottom: 18,
  },
  championRule: {
    width: 72,
    height: 1,
    background: "rgba(255,255,255,.16)",
    margin: "0 auto 16px",
  },
  championSub: {
    fontSize: 14,
    lineHeight: 1.4,
    opacity: 0.7,
  },
  swipeZone: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 84,
    zIndex: 9,
    background: "transparent",
  },
  sheet: {
    position: "absolute",
    left: 10,
    right: 10,
    bottom: -2,
    height: 452,
    zIndex: 16,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    background: "rgba(8,10,14,.82)",
    backdropFilter: "blur(18px)",
    WebkitBackdropFilter: "blur(18px)",
    border: "1px solid rgba(255,255,255,.06)",
    boxShadow: "0 -20px 54px rgba(0,0,0,.32)",
    overflow: "hidden",
  },
  sheetHandleTap: {
    paddingTop: 10,
    paddingBottom: 10,
    display: "flex",
    justifyContent: "center",
    cursor: "pointer",
  },
  sheetHandle: {
    width: 30,
    height: 4,
    borderRadius: 999,
    background: "rgba(255,255,255,.12)",
  },
  sheetHeader: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    padding: "0 18px 14px",
  },
  sheetEyebrow: {
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: "0.22em",
    opacity: 0.46,
    marginBottom: 6,
  },
  sheetTitle: {
    fontSize: 21,
    fontWeight: 800,
    lineHeight: 1.02,
  },
  sheetUpload: {
    width: 34,
    height: 34,
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,.08)",
    background: "rgba(255,255,255,.04)",
    color: "#fff",
    fontSize: 22,
    cursor: "pointer",
  },
  sheetList: {
    padding: "0 10px 18px",
    overflowY: "auto",
    height: 365,
  },
  sheetRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 10px",
    borderRadius: 16,
    border: "1px solid rgba(255,255,255,.04)",
    background: "rgba(255,255,255,.02)",
    marginBottom: 8,
  },
  sheetRank: {
    width: 40,
    fontSize: 13,
    fontWeight: 800,
  },
  sheetText: {
    flex: 1,
    minWidth: 0,
  },
  sheetItemTitle: {
    fontSize: 14,
    fontWeight: 800,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  sheetItemCreator: {
    fontSize: 12,
    opacity: 0.58,
    marginTop: 2,
  },
  sheetRight: {
    textAlign: "right",
  },
  sheetRating: {
    fontSize: 14,
    fontWeight: 800,
  },
  sheetConfidence: {
    fontSize: 11,
    opacity: 0.58,
    marginTop: 2,
  },
  uploadOverlay: {
    position: "absolute",
    inset: 0,
    zIndex: 32,
    background: "rgba(4,6,10,.52)",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    padding: 12,
  },
  uploadCard: {
    width: "min(720px, 100%)",
    maxHeight: "88vh",
    overflowY: "auto",
    borderRadius: 28,
    border: "1px solid rgba(255,255,255,.08)",
    background: "linear-gradient(180deg, rgba(13,17,24,.98), rgba(8,10,14,.98))",
    boxShadow: "0 24px 80px rgba(0,0,0,.45)",
    padding: 18,
  },
  uploadHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 14,
  },
  uploadEyebrow: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.2em",
    opacity: 0.46,
    marginBottom: 5,
  },
  uploadTitle: {
    fontSize: 26,
    fontWeight: 800,
    lineHeight: 1,
  },
  closeButton: {
    width: 34,
    height: 34,
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,.08)",
    background: "rgba(255,255,255,.04)",
    color: "#fff",
    fontSize: 22,
    cursor: "pointer",
  },
  uploadGrid: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    marginBottom: 14,
  },
  field: {
    display: "grid",
    gap: 6,
    fontSize: 12,
    fontWeight: 700,
    opacity: 0.84,
  },
  input: {
    width: "100%",
    borderRadius: 14,
    border: "1px solid rgba(255,255,255,.08)",
    background: "rgba(255,255,255,.04)",
    color: "#fff",
    padding: "12px 12px",
    outline: "none",
  },
  uploadButtons: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    marginBottom: 14,
  },
  uploadButton: {
    flex: 1,
    minWidth: 140,
    borderRadius: 14,
    border: "1px solid rgba(255,255,255,.08)",
    background: "rgba(255,255,255,.04)",
    color: "#fff",
    padding: "12px 14px",
    fontWeight: 800,
    cursor: "pointer",
  },
  previewBox: {
    borderRadius: 20,
    border: "1px solid rgba(255,255,255,.08)",
    background: "rgba(255,255,255,.03)",
    padding: 12,
    marginBottom: 14,
  },
  previewEmpty: {
    minHeight: 150,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    fontSize: 14,
    lineHeight: 1.5,
    opacity: 0.62,
    padding: 20,
  },
  cropHeader: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
    fontWeight: 800,
    fontSize: 13,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  battlePreviewFrame: {
    width: "100%",
    aspectRatio: "9 / 8",
    borderRadius: 18,
    overflow: "hidden",
    background: "#050608",
    border: "1px solid rgba(255,255,255,.12)",
    position: "relative",
    boxShadow: "inset 0 0 0 1px rgba(255,255,255,.04)",
  },
  previewBattleMedia: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    objectPosition: "center center",
    display: "block",
    background: "#08090c",
  },
  cropGuideVertical: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "50%",
    width: 1,
    background: "rgba(255,255,255,.18)",
    zIndex: 4,
    pointerEvents: "none",
  },
  cropGuideHorizontal: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "50%",
    height: 1,
    background: "rgba(255,255,255,.18)",
    zIndex: 4,
    pointerEvents: "none",
  },
  cropFrameLabel: {
    position: "absolute",
    right: 10,
    bottom: 10,
    zIndex: 5,
    padding: "5px 8px",
    borderRadius: 999,
    background: "rgba(0,0,0,.46)",
    border: "1px solid rgba(255,255,255,.12)",
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: "0.12em",
  },
  cropNote: {
    marginTop: 8,
    marginBottom: 10,
    fontSize: 12,
    opacity: 0.56,
  },
  trimRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 10,
    marginBottom: 12,
    fontSize: 12,
    opacity: 0.75,
  },
  sliderLabel: {
    display: "grid",
    gap: 6,
    fontSize: 12,
    fontWeight: 700,
    opacity: 0.72,
    marginBottom: 10,
  },
  slider: {
    width: "100%",
  },
  uploadActions: {
    display: "flex",
    gap: 10,
  },
  cancelButton: {
    flex: 1,
    borderRadius: 16,
    border: "1px solid rgba(255,255,255,.08)",
    background: "rgba(255,255,255,.04)",
    color: "#fff",
    padding: "12px 14px",
    fontWeight: 800,
    cursor: "pointer",
  },
  saveButton: {
    flex: 1,
    borderRadius: 16,
    border: "none",
    background: "linear-gradient(180deg, #7c3aed, #5b21b6)",
    color: "#fff",
    padding: "12px 14px",
    fontWeight: 800,
    cursor: "pointer",
  },
  fallback: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    padding: 22,
  },
  fallbackArena: {
    fontSize: 11,
    letterSpacing: "0.18em",
    opacity: 0.7,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  fallbackTitle: {
    fontSize: 30,
    fontWeight: 800,
    lineHeight: 1,
    marginBottom: 6,
  },
  fallbackCreator: {
    fontSize: 15,
    opacity: 0.72,
  },
  empty: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    padding: 24,
    background: "#050608",
  },
  emptyTitle: {
    fontSize: 26,
    fontWeight: 800,
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 15,
    lineHeight: 1.5,
    opacity: 0.68,
    maxWidth: 360,
    marginBottom: 18,
  },
  emptyButton: {
    borderRadius: 16,
    border: "none",
    background: "linear-gradient(180deg, #7c3aed, #5b21b6)",
    color: "#fff",
    padding: "12px 16px",
    fontWeight: 800,
    cursor: "pointer",
  },
};
